-- MySQL Script generated by MySQL Workbench
-- Thu Oct 29 22:43:03 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cell_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cell_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cell_db` DEFAULT CHARACTER SET utf8 ;
USE `cell_db` ;

-- -----------------------------------------------------
-- Table `cell_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cell_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `avatar` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(100) NULL,
  `ciudad` VARCHAR(45) NULL,
  `provincia` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cell_db`.`trademark`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cell_db`.`trademark` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `image` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cell_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cell_db`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  `price` INT NOT NULL,
  `colors` VARCHAR(45) NOT NULL,
  `company` VARCHAR(45) NOT NULL,
  `discount` INT NOT NULL,
  `dualsim` VARCHAR(45) NOT NULL,
  `capacidad` INT NOT NULL,
  `image` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `id_trademark` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idTrademark_idx` (`id_trademark` ASC),
  CONSTRAINT `idTrademark`
    FOREIGN KEY (`id_trademark`)
    REFERENCES `cell_db`.`trademark` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cell_db`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cell_db`.`carts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_productos` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `remito` INT NOT NULL,
  `date` DATE NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  INDEX `id_usuario_idx` (`id_usuario` ASC),
  INDEX `id_producto_idx` (`id_productos` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `cell_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_producto`
    FOREIGN KEY (`id_productos`)
    REFERENCES `cell_db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
